import React from 'react'

const about = () => {
  return (
    <div className='about'>
      Lorem ipsum dolor sit amet consectetur adipisicing elit. Illo nihil nisi animi aut explicabo magni doloribus vel dolorem doloremque! Officia reiciendis labore possimus aliquid? Eos, tempora ipsum magni doloremque voluptatum nemo! Alias itaque culpa ab ipsum tenetur officiis, repellat cum voluptatibus obcaecati, explicabo aperiam soluta quos eaque enim quam voluptatum nostrum numquam voluptas! Recusandae iste, tempore aliquam, laborum totam non itaque, ipsa explicabo ducimus ea aut est at quo alias magni eum animi consequuntur esse sed autem qui fugiat illo sint vero! Similique laboriosam explicabo laborum, qui inventore voluptatem enim blanditiis. Corrupti, nisi ad! Ad unde velit architecto fuga, iusto expedita rem quam explicabo doloremque quos minima similique quae provident, deserunt accusamus excepturi repellendus recusandae nobis vitae dolorem? Debitis eos officiis aliquid odio, eaque dolores distinctio, harum praesentium sequi repudiandae eligendi unde! Distinctio alias est deleniti soluta, quos ipsa tempora nulla eveniet provident facilis illo sed debitis optio ad ullam animi obcaecati dignissimos perspiciatis, harum excepturi consequuntur reiciendis suscipit laboriosam eaque? Rem est sapiente ut commodi reiciendis maiores tempora, magnam, iste non sunt enim optio mollitia fugit provident dignissimos aspernatur suscipit. Expedita aliquid esse eaque eum nulla saepe est, dolorum dolor fugiat quia, itaque laudantium non! Maiores, nihil obcaecati eius non, sapiente ut qui quasi earum sint ea harum quam ab blanditiis magni facere ullam ex ad commodi corporis aliquam provident illo. Consequuntur alias deleniti sint id sed voluptatum. Itaque accusamus debitis, sapiente optio at culpa vero laboriosam eaque ex praesentium dignissimos aut minus laborum? Fugiat nulla facere illo consequuntur, ex sunt nisi nemo a id ab, dolores doloribus beatae odit similique laboriosam nesciunt obcaecati reprehenderit eum! Maiores, animi veniam minima repellendus recusandae harum quia. Inventore ea soluta ipsum aspernatur amet molestias debitis cupiditate blanditiis commodi sunt asperiores repudiandae hic vero nesciunt maiores, sapiente a quisquam labore maxime laboriosam? Porro consectetur accusamus accusantium libero nostrum aperiam veniam voluptate maxime veritatis, ex suscipit nisi ducimus minus nulla ea modi laborum repellat quam dolorum reiciendis aut! Neque tempora dolorem, mollitia exercitationem suscipit quo inventore voluptatum!
    </div>
  )
}

export default about
